apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
spec:
  replicas: 2 # Set the number of replicas you want to run
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
        - name: api-server
          image: doitmin/docker-image-tttruck-api:prod
          ports:
            - containerPort: 3000 # Replace with the port your Express.js app is listening on
          env:
            - name: DB_HOST
              value: <your-mariadb-service-name> # Replace with the name of your MariaDB service
